# Generated by Django 4.0.3 on 2022-03-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Type',
            field=models.CharField(choices=[('n', 'novel'), ('m', 'magazine'), ('n', 'newspaper'), ('t', 'tools')], max_length=1),
        ),
    ]
