# Generated by Django 4.0.3 on 2022-03-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_alter_book_author_alter_bookinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='passport',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
