# Generated by Django 4.1.1 on 2023-01-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("races", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
