# Generated by Django 4.1.1 on 2023-01-16 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("race", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="rider", name="rider_description",),
        migrations.RemoveField(model_name="rider", name="rider_experience",),
        migrations.AddField(
            model_name="rider",
            name="description",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="rider",
            name="experience",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="comment", name="text", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="comment",
            name="type",
            field=models.CharField(
                choices=[
                    ("1", "вопрос о сотрудничестве"),
                    ("2", "вопрос о гонках"),
                    ("3", "иное"),
                ],
                default=("1", "вопрос о сотрудничестве"),
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="rider",
            name="car_description",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="rider",
            name="class_type",
            field=models.CharField(
                choices=[("1", "A junior"), ("2", "B middle"), ("3", "C senior")],
                default=("1", "A junior"),
                max_length=1,
            ),
        ),
        migrations.DeleteModel(name="Comment_type",),
        migrations.DeleteModel(name="Rider_class_type",),
    ]
